# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://special-funicular-7gvx4jg7p9q2wp5q-8080.app.github.dev

### Inserir nova pessoa
POST {{ base_url }}/api/pessoas
Content-Type: application/json

{
  "nome": "Gabriel",
  "idade": 28
}

### Listar todas as pessoas
GET {{ base_url }}/api/pessoas
Accept: application/json

### Buscar pessoa por ID
GET {{ base_url }}/api/pessoas/3
Accept: application/json

### Atualizar pessoa (PUT)
PUT {{ base_url }}/api/pessoas/1
Content-Type: application/json

{
  "nome": "Rafael Marinho",
  "idade": 35
}

### Remover pessoa (DELETE)
DELETE {{ base_url }}/api/pessoas/1
Accept: */*



#############
POST {{ base_url }}/api/produtos
Content-Type: application/json

{
  "nome": "Baixo",
  "quantidade": 2,
  "preco": 3500.00
}

GET {{ base_url }}/api/produtos
Accept: application/json

GET {{ base_url }}/api/produtos/1
Accept: application/json

PUT {{ base_url }}/api/produtos/1
Content-Type: application/json

{
  "nome": "Baixo",
  "quantidade": 5,
  "preco": 4500.00
}

### Remover produto (DELETE)
DELETE {{ base_url }}/api/produtos/1
Accept: */*